DROP TRIGGER payments_no_change ON payments;
DROP FUNCTION payments_guard();
CREATE TRIGGER payments_no_change BEFORE UPDATE OR DELETE ON payments FOR EACH ROW EXECUTE FUNCTION payments_immutable();
ALTER TABLE sale_refunds DROP CONSTRAINT sale_refunds_target_chk;
ALTER TABLE sale_refunds DROP COLUMN order_id;
ALTER TABLE sale_refunds ALTER COLUMN sale_id SET NOT NULL;
ALTER TABLE payments DROP CONSTRAINT payments_target_chk;
DROP INDEX payments_order_idx;
ALTER TABLE payments DROP COLUMN order_id;
ALTER TABLE payments ALTER COLUMN sale_id SET NOT NULL;
ALTER TABLE sales DROP COLUMN order_id;
DROP TABLE deliveries;
DROP TABLE delivery_routes;
DROP TABLE delivery_zones;
DROP TABLE production_checklist;
DROP TABLE production_orders;
DROP TABLE stock_reservations;
DROP TABLE order_status_history;
DROP TABLE order_items;
DROP TABLE orders;
